server:
  port: 8001
  servlet:
    session:
      #Session超时时间设置为5小时，单位是秒，默认是30分钟
      timeout: 18000
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://47.101.202.81:3306/rmxg_blog
    username: root
    password: qQ@2191826738!
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    settings:
      classic_compatible: true
      number_format: 0.##
      datetime_format: yyyy-MM-dd HH:mm:ss
  web:
    resources:
      static-locations:
        classpath: /static/

mybatis-plus:
  type-aliases-package: com.example.rmxg_blog.entity
  configuration:
    call-setters-on-nulls: false
    #开启驼峰
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full

  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    banner: true
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      logic-not-delete-value: 1
      logic-delete-value: 0
      id-type: assign_uuid


#logging:
#  level:
#    root: error #日志配置DEBUG,INFO,WARN,ERROR